kind: PersistentVolume
apiVersion: v1
metadata:
  name: backup
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage/backup"
